### PR TITLE
Added Orchard skin

### PR DESCRIPTION
**Pull request by l4rs3rik**
This is the version 1.2 of the Orchard skin.

### CODE REVIEW

**Comment by fredli74** [comment]
Nice 🤘🏻

Is the thumbnail supposed to have no logo, default logo, or your custom logo? Either is fine, just asking before merging.

**Comment by l4rs3rik** [comment]
If it's ok with you I'll add my custom logotype to the skin (and to the thumbnail).

**Comment by fredli74** [comment]
Yeah sure, I like skin variety!

**Comment by l4rs3rik** [comment]
Ok, I'll do an update/commit with the custom logo.

**Comment by l4rs3rik** [comment]
I've pushed the 1.2 version now with a slightly adjusted custom logo and some minor tweaks.

**Pull request merged**
